### ISSUE TITLE
from Dual error in Oracle

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Iris#3]
The code has a known bug for Oracle db Engine. (found thanks to the team at Regenstrief)

The code will not run on Oracle database. You can manually fix it by grabing the code from the SQL error and adding 'from dual' as in this code (for G1 measure):

iris_event AS ( --- CTE
    select
        TO_CHAR('G1' ) AS measure,
        CAST(a.cnt AS NUMBER(19)) AS result,
        TO_CHAR('count of events' ) AS explanation
    FROM (
      select
            (select COUNT(_)   from omopv5_de.person)
            +(select COUNT(_)  from omopv5_de.observation)
            +(select COUNT(_)  from omopv5_de.condition_occurrence)
            +(select COUNT(_)  from omopv5_de.drug_exposure)
            +(select COUNT(_)  from omopv5_de.visit_occurrence)
            +(select COUNT(_)  from omopv5_de.death)
            +(select COUNT(*)  from omopv5_de.procedure_occurrence) cnt from dual
    ) a
),

**Comment by schuemie** [comment]
Please try the latest version of SqlRender. This problem should have been fixed in [this commit](https://github.com/OHDSI/SqlRender/commit/e90a58915817f3f261f6f94e626d12edd7348481).

**Comment by vojtechhuser** [comment]
thanks for the fix.
